-- OmniMerchant v2 observability and trajectory replay tables.
-- Run after sql/db_main.sql and sql/db_extensions.sql.

CREATE TABLE IF NOT EXISTS `agent_run` (
  `id` BIGINT NOT NULL,
  `tenant_id` BIGINT NOT NULL,
  `trace_id` VARCHAR(64) NOT NULL,
  `conversation_uuid` VARCHAR(64) DEFAULT NULL,
  `run_type` VARCHAR(32) NOT NULL DEFAULT 'CHAT',
  `intent` VARCHAR(64) DEFAULT NULL,
  `model_provider` VARCHAR(32) DEFAULT NULL,
  `model_name` VARCHAR(64) DEFAULT NULL,
  `router_decision` VARCHAR(256) DEFAULT NULL,
  `input_redacted` VARCHAR(2048) DEFAULT NULL,
  `input_hash` VARCHAR(64) DEFAULT NULL,
  `final_answer_redacted` TEXT DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
  `failure_category` VARCHAR(64) DEFAULT NULL,
  `failure_reason` VARCHAR(1024) DEFAULT NULL,
  `prompt_tokens` BIGINT NOT NULL DEFAULT 0,
  `completion_tokens` BIGINT NOT NULL DEFAULT 0,
  `cost_usd` DECIMAL(12,6) NOT NULL DEFAULT 0.000000,
  `first_token_latency_ms` INT DEFAULT NULL,
  `total_latency_ms` INT DEFAULT NULL,
  `tool_call_count` INT NOT NULL DEFAULT 0,
  `retrieved_doc_count` INT NOT NULL DEFAULT 0,
  `citation_count` INT NOT NULL DEFAULT 0,
  `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finished_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_trace_id` (`trace_id`),
  KEY `idx_tenant_started` (`tenant_id`, `started_at`),
  KEY `idx_tenant_status` (`tenant_id`, `status`, `started_at`),
  KEY `idx_conversation` (`tenant_id`, `conversation_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent execution run trace';

CREATE TABLE IF NOT EXISTS `agent_step` (
  `id` BIGINT NOT NULL,
  `tenant_id` BIGINT NOT NULL,
  `agent_run_id` BIGINT NOT NULL,
  `trace_id` VARCHAR(64) NOT NULL,
  `step_index` INT NOT NULL,
  `step_type` VARCHAR(32) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'SUCCESS',
  `input_summary` VARCHAR(2048) DEFAULT NULL,
  `output_summary` VARCHAR(2048) DEFAULT NULL,
  `tool_call_id` VARCHAR(64) DEFAULT NULL,
  `latency_ms` INT DEFAULT NULL,
  `failure_category` VARCHAR(64) DEFAULT NULL,
  `failure_reason` VARCHAR(1024) DEFAULT NULL,
  `metadata_json` TEXT DEFAULT NULL,
  `started_at` DATETIME DEFAULT NULL,
  `ended_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_trace_step` (`trace_id`, `step_index`),
  KEY `idx_run_step` (`agent_run_id`, `step_index`),
  KEY `idx_tool_call` (`tool_call_id`),
  KEY `idx_tenant_type` (`tenant_id`, `step_type`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Agent trajectory step trace';
